spring:
  application:
    name: communications-center
  datasource:
    url: jdbc:h2:mem:communicationsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_UPPER=false
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: INFO
    com.example.communications: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info

scheduler:
  communication:
    cron: 0 0 6 * * *
